apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-svc
spec:
  hosts:
  - frontend
  http:
  - route:
    - destination:
        host: frontend
        subset: v8-final
